<script lang="ts">
	import type { PageData } from './$types';
	import { cubicInOut } from 'svelte/easing';

	import { scaleBand } from 'd3-scale';
	import { BarChart, type ChartContextValue } from 'layerchart';

	import * as Chart from '$lib/components/ui/chart';
	import { Card } from '$lib/components/ui/card';
	import { getModelName, models } from '$lib/models';

	let { data }: { data: PageData } = $props();

	function getProviderColor(modelId: string): string {
		const model = models.find((m) => m.id === modelId);
		if (!model) return '#6b7280'; // Default gray for unknown models

		const providerId = model.provider.id;
		switch (providerId) {
			case 'google':
				return '#6a93f0'; // Blue for Google
			case 'openai':
				return '#187746'; // Green for OpenAI
			case 'anthropic':
				return '#d97757'; // Orange for Anthropic
			case 'xai':
				return '#374151'; // Dark gray for xAI
			default:
				return '#6b7280'; // Default gray
		}
	}

	const messageChartData = $derived(
		data.modelMessageStats.map((stat) => {
			const displayName = getModelName(stat.modelId);
			const color = getProviderColor(stat.modelId);
			return {
				model: displayName.length > 15 ? displayName.substring(0, 15) + '...' : displayName,
				fullModel: displayName,
				messages: stat.messageCount,
				color: color
			};
		})
	);

	const tokenChartData = $derived(
		data.modelTokenStats.map((stat) => {
			const displayName = getModelName(stat.modelId);
			const color = getProviderColor(stat.modelId);
			return {
				model: displayName.length > 15 ? displayName.substring(0, 15) + '...' : displayName,
				fullModel: displayName,
				tokens: stat.totalTokens,
				color: color
			};
		})
	);

	const messageChartConfig = {
		messages: { label: 'Messages', color: 'var(--chart-1)' }
	} satisfies Chart.ChartConfig;

	const tokenChartConfig = {
		tokens: { label: 'Tokens', color: 'var(--chart-2)' }
	} satisfies Chart.ChartConfig;

	let messageContext = $state<ChartContextValue>();
	let tokenContext = $state<ChartContextValue>();

	const totalTokens = $derived(
		data.modelTokenStats.reduce((sum, stat) => sum + stat.totalTokens, 0)
	);

	const totalMessages = $derived(
		data.modelMessageStats.reduce((sum, stat) => sum + stat.messageCount, 0)
	);

	const uniqueModels = $derived(new Set(data.modelMessageStats.map((stat) => stat.modelId)).size);
</script>

<svelte:head>
	<title>Usage Statistics</title>
</svelte:head>

<div class="mx-auto max-w-4xl p-4">
	<header class="pt-16 pb-6">
		<div class="space-y-1">
			<h1 class="text-2xl font-bold tracking-tight">Usage Statistics</h1>
			<p class="text-muted-foreground text-sm">
				View your model usage patterns, token consumption, and message statistics.
			</p>
		</div>
	</header>

	<main class="space-y-8 pt-6">
		<div class="grid gap-4 md:grid-cols-3">
			<Card class="p-6">
				<div class="space-y-2">
					<p class="text-sm font-medium">Models Used</p>
					<p class="text-2xl font-bold">{uniqueModels}</p>
					<p class="text-muted-foreground text-xs">Different models utilized</p>
				</div>
			</Card>
			<Card class="p-6">
				<div class="space-y-2">
					<p class="text-sm font-medium">Total Messages</p>
					<p class="text-2xl font-bold">{totalMessages.toLocaleString()}</p>
					<p class="text-muted-foreground text-xs">Assistant responses generated</p>
				</div>
			</Card>
			<Card class="p-6">
				<div class="space-y-2">
					<p class="text-sm font-medium">Total Tokens</p>
					<p class="text-2xl font-bold">{totalTokens.toLocaleString()}</p>
					<p class="text-muted-foreground text-xs">Tokens consumed across all models</p>
				</div>
			</Card>
		</div>

		<div class="grid gap-6 lg:grid-cols-2">
			<Card class="p-6">
				<div class="space-y-4">
					<div>
						<h3 class="font-medium">Messages by Model</h3>
						<p class="text-muted-foreground text-sm">Number of responses generated by each model</p>
					</div>
					<Chart.Container config={messageChartConfig}>
						<BarChart
							bind:context={messageContext}
							data={messageChartData}
							xScale={scaleBand().padding(0.25)}
							x="model"
							y="messages"
							axis="x"
							cRange={messageChartData.map((d) => d.color)}
							c="color"
							rule={false}
							props={{
								bars: {
									stroke: 'none',
									strokeWidth: 0,
									rounded: 'all',
									initialY: messageContext?.height,
									initialHeight: 0,
									motion: {
										y: { type: 'tween', duration: 500, easing: cubicInOut },
										height: { type: 'tween', duration: 500, easing: cubicInOut }
									}
								},
								highlight: { area: { fill: 'none' } },
								xAxis: { format: (d) => d.slice(0, 12) }
							}}
						>
							{#snippet tooltip()}
								<Chart.Tooltip hideLabel nameKey="messages" />
							{/snippet}
						</BarChart>
					</Chart.Container>
				</div>
			</Card>

			<Card class="p-6">
				<div class="space-y-4">
					<div>
						<h3 class="font-medium">Tokens by Model</h3>
						<p class="text-muted-foreground text-sm">Total token consumption by each model</p>
					</div>
					<Chart.Container config={tokenChartConfig}>
						<BarChart
							bind:context={tokenContext}
							data={tokenChartData}
							xScale={scaleBand().padding(0.25)}
							x="model"
							y="tokens"
							axis="x"
							cRange={tokenChartData.map((d) => d.color)}
							c="color"
							rule={false}
							props={{
								bars: {
									stroke: 'none',
									strokeWidth: 0,
									rounded: 'all',
									initialY: tokenContext?.height,
									initialHeight: 0,
									motion: {
										y: { type: 'tween', duration: 500, easing: cubicInOut },
										height: { type: 'tween', duration: 500, easing: cubicInOut }
									}
								},
								highlight: { area: { fill: 'none' } },
								xAxis: { format: (d) => d.slice(0, 12) }
							}}
						>
							{#snippet tooltip()}
								<Chart.Tooltip hideLabel nameKey="tokens" />
							{/snippet}
						</BarChart>
					</Chart.Container>
				</div>
			</Card>
		</div>
	</main>
</div>
